### ISSUE TITLE
SqlConnection reuse / MultipleActiveResultSets=true

### ISSUE THREAD

**Issue by AurelianTimu** [kgrzybek/modular-monolith-with-ddd#122]
Hi,

When a new `User` is created via `/userAccess/UserRegistrations`, the handlers in other modules which are subscribed to `NewUserRegisteredIntegrationEvent` throw the error below. The issue seems to be related to`SELECT`/`UPDATE` statements performed using Dapper in inbox processing (`ProcessInboxCommandHandler`) and reusing the sql connection.

```
[19:09:45 INF] [UserAccess] [OutboxMessage:cd855ef7-de09-491b-93a1-8e22e426bc8f] Publishing CompanyName.MyMeetings.Modules.UserAccess.IntegrationEvents.NewUserRegisteredIntegrationEvent
[19:09:46 ERR] [Payments] [] Job DEFAULT.a5b45b20-44cf-4cda-9334-d412a7af9b9b threw an unhandled Exception:
System.InvalidOperationException: The connection does not support MultipleActiveResultSets.
   at System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
   at System.Data.SqlClient.SqlCommand.ValidateCommand(Boolean async, String method)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.BeginExecuteNonQuery(AsyncCallback callback, Object stateObject)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory`1.FromAsync(Func`3 beginMethod, Func`2 endMethod, Object state)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
   at CompanyName.MyMeetings.Modules.Administration.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\Projects\dev\dotnet\tests\modular-monolith-with-ddd\src\Modules\Administration\Infrastructure\Configuration\Processing\Inbox\ProcessInboxCommandHandler.cs:line 60
   at CompanyName.MyMeetings.Modules.Administration.Infrastructure.Configuration.Processing.UnitOfWorkCommandHandlerWithResultDecorator`2.Handle(T command, CancellationToken cancellationToken) in C:\Projects\dev\dotnet\tests\modular-monolith-with-ddd\src\Modules\Administration\Infrastructure\Configuration\Processing\UnitOfWorkCommandHandlerWithResultDecorator.cs:line 31
   at CompanyName.MyMeetings.Modules.Administration.Infrastructure.Configuration.Processing.LoggingCommandHandlerWithResultDecorator`2.Handle(T command, CancellationToken cancellationToken) in C:\Projects\dev\dotnet\tests\modular-monolith-with-ddd\src\Modules\Administration\Infrastructure\Configuration\Processing\LoggingCommandHandlerWithResultDecorator.cs:line 35
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at CompanyName.MyMeetings.Modules.Administration.Infrastructure.Configuration.Processing.CommandsExecutor.Execute[TResult](ICommand`1 command) in C:\Projects\dev\dotnet\tests\modular-monolith-with-ddd\src\Modules\Administration\Infrastructure\Configuration\Processing\CommandsExecutor.cs:line 24
   at CompanyName.MyMeetings.Modules.Administration.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\Projects\dev\dotnet\tests\modular-monolith-with-ddd\src\Modules\Administration\Infrastructure\Configuration\Processing\Inbox\ProcessInboxJob.cs:line 11
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
```

When adding `MultipleActiveResultSets=True` to the db connection string, the issue obviously disappears.
I would avoid using MARS (`MultipleActiveResultSets=true`) if possible.

Environment : running on Windows, with a localhost SQL Server
Let me know if additional details are needed.

Thanks.

**Comment by kgrzybek** [comment]
Hi @AurelianTimu 

Unfortunately, I cannot reproduce this issue. I removed `MultipleActiveResultSets=True` and even tried `MultipleActiveResultSets=False` and still handlers work correctly. Running on the same envirionment: Windows + locahost SQL Server (Express 2017).

I would not say the reason is connection reusing. All connections are managed by `SqlConnectionFactory` which is `IDisposable`. and registered as `PerLifetimeScope`. All commands/queries processing has lifetime scope so the connection is closed at the end of each processing.

Could you provide more details? Or maybe you can check it once again? There were some changes since that time

**Comment by PabloFerroDev** [comment]
Hi @kgrzybek ! We are having the exact same issue. Which details would be convenient for you?

**Comment by PiotrWachulec** [comment]
Hi @kgrzybek , I can confirm that I had to add `MultipleActiveResultSets=True` to run app correctly. I did it on Ubuntu + MSSQL in Docker container.

**Comment by kgrzybek** [comment]
I didn't have time to check this issue. Maybe in the meantime, someone has resolved it?

**Comment by kgrzybek** [comment]
I resolved this issue myself. The reason was missing `await` before command scheduling action:
```csharp
_commandsScheduler.EnqueueAsync(...
```

I changed to 
```csharp
await _commandsScheduler.EnqueueAsync(...
```

and it works.

I don't know why this bug didn't occur on the local MS SQL Server on Windows OS. On Docker I had the issue.

Additionally, I changed InMemoryEventsBus to await/async
